ingest: 
  raw_data_path: ./data/PJME_hourly.csv

train:
  xgboost_params:
    n_estimators:
      - 100
      - 300
      - 500
    max_depth: 
      - 3
      - 6
      - 15
    learning_rate:
      - 0.1
      - 0.3
      - 0.5
    gamma:
      - 0
      - 0.1
      - 1
  catboost_params:
    max_depth:
      - 3
      - 6
    learning_rate:
      - 0.001
      - 0.01
      - 0.1
    min_data_in_leaf:
      - 1
      - 10
      - 100
    